# Generated by Django 4.1.1 on 2022-09-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('DPI', models.CharField(max_length=45, verbose_name='DPI')),
                ('NIT', models.CharField(max_length=45, verbose_name='NIT')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuadreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=45, verbose_name='User')),
                ('password', models.CharField(max_length=45, verbose_name='Password')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('puesto_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45, verbose_name='Tipo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('platillo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(max_length=45, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('C', 'Creada'), ('T', 'Terminada'), ('E', 'Entregada')], default='C', max_length=1)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente')),
                ('colaborador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.colaborador')),
                ('cuadreCaja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuadrecaja')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('cuadreCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuadrecaja')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orden')),
                ('platillo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='puesto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.puesto'),
        ),
    ]
