# Generated by Django 4.1.2 on 2022-10-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tipoplatillo_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoplatillo',
            old_name='precio',
            new_name='PrimerPrecio',
        ),
        migrations.AddField(
            model_name='tipoplatillo',
            name='SegundoPrecio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoplatillo',
            name='TercerPrecio',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
