# Generated by Django 4.1.2 on 2022-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tipoplatillo_tercerprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplatillo',
            name='TercerPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
