# Generated by Django 4.1.2 on 2022-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_precio_tipoplatillo_primerprecio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplatillo',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
