# Generated by Django 4.2 on 2023-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_especialidad_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='imagen',
            field=models.ImageField(default='descarga.png', upload_to='especialidad'),
        ),
    ]
