# Generated by Django 4.1.1 on 2022-10-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_colaborador_perfil'),
        ('home', '0004_alter_tipoplatillo_descripcion'),
    ]

    operations = [
    ]
