# Generated by Django 4.1.2 on 2022-10-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20221025_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='puesto_id',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
