# Generated by Django 4.1.2 on 2022-10-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20221024_1817'),
        ('home', '0007_colaborador_edad_colaborador_telefono_and_more'),
    ]

    operations = [
    ]
