# Generated by Django 4.1.1 on 2022-10-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20221029_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='cuadrecaja',
            name='disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='PrimerPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='SegundoPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoplatillo',
            name='TercerPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
