# Generated by Django 4.1.1 on 2022-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20221029_2200'),
        ('home', '0009_remove_gasto_fecha_alter_cuadrecaja_disponible_and_more'),
    ]

    operations = [
    ]
