# Generated by Django 4.1.2 on 2022-11-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20221029_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='perfil',
        ),
    ]
