# Generated by Django 4.1.1 on 2022-11-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20221029_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
    ]
