# Generated by Django 4.1.2 on 2022-11-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_colaborador_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='puesto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.puesto'),
        ),
    ]
