# Generated by Django 4.1.2 on 2022-11-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_colaborador_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.puesto'),
        ),
    ]
